name: action-check-version

inputs:
  token:
    required: false
    default: ${{ github.token }}
  repository:
    required: false
    default: ${{ github.repository }}
  base-sha:
    required: false
    default: ${{ github.event.pull_request.base.sha }}
  base-branch:
    required: false
    default: ${{ github.event.pull_request.base.ref }}
  comment:
    required: false
    default: true
  comment-same:
    required: false
    default: |
      Version in `{{file}}` from `{{currentBranch}}`
      https://github.com/{{owner}}/{{repo}}/blob/{{currentSha}}/{{file}}#L{{currentLine}}
      is the same as the one in `{{baseBranch}}`
      https://github.com/{{owner}}/{{repo}}/blob/{{baseSha}}/{{file}}#L{{baseLine}}
  comment-smaller:
    required: false
    default: |
      Version in `{{file}}` from `{{currentBranch}}`
      https://github.com/{{owner}}/{{repo}}/blob/{{currentSha}}/{{file}}#L{{currentLine}}
      is smaller then the one in `{{baseBranch}}`
      https://github.com/{{owner}}/{{repo}}/blob/{{baseSha}}/{{file}}#L{{baseLine}}

runs:
  using: 'node20'
  main: 'index.js'
