name: action-check-version

inputs:
  token:
    required: false
    default: ${{ github.token }}
  repository:
    required: false
    default: ${{ github.repository }}
  base-sha:
    required: false
    default: ${{ github.event.pull_request.base.sha }}
  base-branch:
    required: false
    default: ${{ github.event.pull_request.base.ref }}
  current-sha:
    required: false
    default: ${{ github.sha }}
  current-branch:
    required: false
    default: ${{ github.head_ref }}

runs:
  using: 'node20'
  main: 'index.js'
