name: check-version 

on:
  pull_request:
    branches:
      - master 

permissions:
  contents: write
  pull-requests: write

jobs:

  check-version:
    runs-on: ubuntu-latest

    steps:

      - name: Check-version
        uses: ./
